# Generated by Django 4.0.1 on 2022-01-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefitsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('middleName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('provider', models.CharField(max_length=180)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
