# Generated by Django 4.0.1 on 2022-01-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefitsapi', '0002_dependent_alter_package_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependent',
            old_name='provider',
            new_name='providerID',
        ),
        migrations.AlterField(
            model_name='dependent',
            name='middleName',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middleName',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
