# Generated by Django 4.0.1 on 2022-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefitsapi', '0003_rename_provider_dependent_providerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=52000, max_digits=9),
            preserve_default=False,
        ),
    ]
